theme = "adwaita-dark"

[editor]
line-number = "relative"
true-color = true
mouse = true
cursorline = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
color-modes = true
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "position-percentage"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# [editor.whitespace]
# render = "all"
# or control each character
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
"C-S-esc" = "extend_line" # Maps Control-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
"backspace" = { r = ":sh cargo run", s = [":w", ":config-reload"], o = ":config-open", c = ":buffer-close"}

# "backspace" = { s = [":w", ":config-reload"]}
# "backspace" = { c = [":config-open"]}
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

# create a new minor mode bound to `+`
[keys.normal."+"]
r = ":run-shell-command cargo run"
b = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"