# language.toml config for inlay hit

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "go"

[[language]]
name = "lua"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
# language-servers = ["vue-language-server"]

# [language-server.vue-language-server]
# command = "vue-language-server"
# args = "--stdio"

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
# config = { hostinfo = "helix", inlayHintsOptions = { "includeInlayFunctionParameterTypeHints" = true } }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "php"
language-servers = [ "phpactor" ]

[language-server.phpactor]
command = "phpactor"
args = [ "language-server" ]


# [language-server.typescript-language-server.config.typescript.inlayHints]
# includeInlayEnumMemberValueHints = true
# includeInlayFunctionLikeReturnTypeHints = true
# includeInlayFunctionParameterTypeHints = true
# includeInlayParameterNameHints = "all"
# includeInlayParameterNameHintsWhenArgumentMatchesName = true
# includeInlayPropertyDeclarationTypeHints = true
# includeInlayVariableTypeHints = true

